### ISSUE TITLE
[chat] Implement unread messages counter

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#117]
Currently the counter is always displayed as 1 if cookie `chatwasopened` is not set (i.e. user never opened the chat or opened and 20 days passed).

If opened, the chat displays the message `Hi, how can I help?`, this is the correct behaviour and the counter 1 should be shown.

But if user writes something into this chat, leaves the page and received a reply later - the counter does not represent newly received messages (i.e. if I reply to the user in the chat 2 times - there won't be a `2` badge displayed).

When chat gets opened - there's a websocket request happening and in case there are unread messages - they're getting received via this WS connection.
I need you to get the unread messages via this connections, and if there are:
1. no messages - display the `re-open chat` button (as it currently does).
<img width="265" alt="Screenshot 2023-02-04 at 21 36 04" src="https://user-images.githubusercontent.com/35810911/216790526-970e1b6c-6474-469d-9aa5-7471e2adb4ed.png">

2. messages - you should display the correct message counter like on the following screenshot
<img width="345" alt="Screenshot 2023-02-04 at 21 36 52" src="https://user-images.githubusercontent.com/35810911/216790561-6f537e9e-a99f-40cb-9df2-d92cbdee6818.png">

**Comment by Pranavvks** [comment]
Hi @Blaumaus I would like to work on this issue.

**Comment by Pranavvks** [comment]
Hey @kruzhambus. While setting up the development environment for swetrix-api, I have been running into an issue resolving ioredis dependency. However, I'm not sure that this could be the only reason to it.  

Do you recommend any specific version of node to be used for the project ?. I have also attached the debug log. 

Also, the configuration documentation website (for selfhosting)  is not accessible.
[swetrix-api-debug-0.log](https://github.com/Swetrix/roadmap/files/12292513/swetrix-api-debug-0.log)

Cheers ✌️

**Comment by kruzhambus** [comment]
Try npm i -f and watch CONTRIBUTIONS.md

**Comment by Pranavvks** [comment]
> Try npm i -f and watch CONTRIBUTIONS.md

It worked , but for the setup of environment variables the webpage mentioned in the contributions file is not reachable.

**Comment by Pranavvks** [comment]
Hi @kruzhambus. 
The link given within the CONTRIBUTIONS.md for environment variables configuration seems to be broken. However I was able to find it , I believe this is the one we must refer to :  https://docs.swetrix.com/selfhosting/configuring. 

I was able to get the swetrix-api and swetrix-fe up and running. However, it appears that the process of creating a dummy account within the development environment (swetrix-fe) is not concluding successfully. 

Could you kindly assist me in setting up the development environment or provide any helpful links for the same ?.

**Comment by kruzhambus** [comment]
> Hi @kruzhambus. The link given within the CONTRIBUTIONS.md for environment variables configuration seems to be broken. However I was able to find it , I believe this is the one we must refer to : https://docs.swetrix.com/selfhosting/configuring.
> 
> I was able to get the swetrix-api and swetrix-fe up and running. However, it appears that the process of creating a dummy account within the development environment (swetrix-fe) is not concluding successfully.
> 
> Could you kindly assist me in setting up the development environment or provide any helpful links for the same ?.

so sorry I left the wrong link. If you want to deploy our project for development, then this is what you need
[https://github.com/Swetrix/swetrix-api/blob/main/CONTRIBUTING.MD](https://github.com/Swetrix/swetrix-api/blob/main/CONTRIBUTING.MD)

**Comment by Pranavvks** [comment]
No worries @kruzhambus 🙂. I was in fact referring to the same. Within the same guidelines under the set up envrionment variables (part 3) of the CONTRIBUTING.MD file the configuration link is broken. I have attached the screenshot below. I guess it hasn't been updated. 

Further what should I do to resolve the earlier mentioned issue of not being able to create an account within the development environment ?.
<img width="824" alt="Swetrix-404-Selfhosting-Config" src="https://github.com/Swetrix/roadmap/assets/71880387/fc68e87b-a58c-4437-a6fd-bb8dde4a4f54">

**Comment by kruzhambus** [comment]
how did you run dev Swetrix on your machine (was it docker or just npm run start:dev)? which error does the backend throw when you try to sign up locally? @Pranavvks

**Comment by Pranavvks** [comment]
Hi @kruzhambus. I am running the swetrix-api using docker followed by the npm run start:dev command. Currently the backend throws an error:
  
   [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

This happens after the logger shows the Nestjs application has started successfully.

**Comment by yevheniikulisidi** [comment]
Hello there, @Pranavvks! I wanted to make sure you're aware of a crucial step you might have overlooked: [setting up environment variables](https://github.com/Swetrix/swetrix-api/blob/main/CONTRIBUTING.MD#3-set-up-environment-variables). This step is essential for the process. Don't forget to give it a look!

**Comment by Pranavvks** [comment]
Hi @yevheniikulisidi. Yup, I did follow the environment configuration setup as per your guidelines listed in this webpage : https://docs.swetrix.com/selfhosting/configuring. Upon your comment, I also made a check confirming whether my env configuration matches your spec and there seems to be no problem. 

For your reference I have attached the env configuration :
[Env.txt](https://github.com/Swetrix/roadmap/files/12327420/Env.txt)

**Comment by yevheniikulisidi** [comment]
I noticed that you've made changes to the environment variables like `REDIS_HOST`, `REDIS_PASSWORD`, and `CLICKHOUSE_HOST`, @Pranavvks. However, I'd recommend avoiding these changes and sticking to the original specifications outlined in the [.env.example](https://github.com/Swetrix/swetrix-api/blob/main/.env.example) file. This approach would be more preferable.

**Comment by Pranavvks** [comment]
@yevheniikulisidi I was able to resolve that issue after making the changes to the env conifguration. However I am still not able to create an account within the dev environment. Nothing happens in the sign up process , it remains in an indefinite cycle. 

Additionaly, there are no error messages within the console.

**Comment by yevheniikulisidi** [comment]
To create an account, @Pranavvks, you can utilize the API by sending a direct request. Here's how:

1. Navigate to the Swagger documentation page: [Swagger Documentation - AuthController_register](http://localhost:5005/api#/Auth/AuthController_register).
2. Click on the "Try it out" button.
3. Then, click on "Execute".

Once you've completed these steps, you can try logging into the newly created account through the Swetrix FE interface.

**Comment by Pranavvks** [comment]
@yevheniikulisidi I tried out the steps mentioned, but still not able to log in through the Swetrix FE interface. 

The account gets created via the swagger ui. However using the same account credentials I'm not able to log in. Currently I'm receiving the following error in the frontend : 

ErrorResponse {
  status: 405,
  statusText: 'Method Not Allowed',
  internal: true,
  data: 'Error: You made a POST request to "/v1/auth/login" but did not provide an `action` for route "routes/$", so there is no way to handle the request.',
  error: Error: You made a POST request to "/v1/auth/login" but did not provide an `action` for route "routes/$", so there is no way to handle the request.
      at getInternalRouterError (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:4132:5)
      at submit (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2816:19)
      at queryImpl (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2764:28)
      at Object.query (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2650:24)
      at handleDocumentRequestRR (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/server-runtime/dist/server.js:170:35)
      at requestHandler (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/server-runtime/dist/server.js:61:24)
      at /Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/express/dist/server.js:39:28
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}

**Comment by Blaumaus** [comment]
> @yevheniikulisidi I tried out the steps mentioned, but still not able to log in through the Swetrix FE interface. 
> 
> The account gets created via the swagger ui. However using the same account credentials I'm not able to log in. Currently I'm receiving the following error in the frontend : 
> 
> ErrorResponse {
>   status: 405,
>   statusText: 'Method Not Allowed',
>   internal: true,
>   data: 'Error: You made a POST request to "/v1/auth/login" but did not provide an `action` for route "routes/$", so there is no way to handle the request.',
>   error: Error: You made a POST request to "/v1/auth/login" but did not provide an `action` for route "routes/$", so there is no way to handle the request.
>       at getInternalRouterError (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:4132:5)
>       at submit (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2816:19)
>       at queryImpl (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2764:28)
>       at Object.query (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/router/router.ts:2650:24)
>       at handleDocumentRequestRR (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/server-runtime/dist/server.js:170:35)
>       at requestHandler (/Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/server-runtime/dist/server.js:61:24)
>       at /Users/pranavsudhir/Documents/Development/swetrix-fe/node_modules/@remix-run/express/dist/server.js:39:28
>       at processTicksAndRejections (node:internal/process/task_queues:96:5)
> }
> 
> 
> 
> 

As I understood, you're only running dependecies via docker (i.e. only clickhouse and redis), right? If that's the case, then you have to set up link to Swetrix API (should be something like http://localhost:5005) in the swetrix-fe .env file. That will resolve the issue.

I'm not sure if you can run the Swetrix Frontend itself via docker as we recently migrated to Remix and I did not properly test it with Docker.

So the set up process should look like that:
1. Run the dependencies container (docker-compose-dev.yml in swetrix-api)
2. Set up .env for the API (I see you've already done that) and start it up via the `npm run start:dev` command.
3. Set up .env for swetrix-fe and start it up with the `npm run dev` command.

I'll send you my swetrix-fe .env config in the next message.

**Comment by Blaumaus** [comment]
@Pranavvks here's my swetrix-fe .env config:
```
API_URL=https://api.swetrix.com/
API_STAGING_URL=http://localhost:5005/
CDN_URL=https://cdn.swetrix.com/
BLOG_URL=https://blog.swetrix.com/
AIAPI_URL=https://aiapi.swetrix.com/
```

**Comment by Blaumaus** [comment]
Also @Pranavvks, this may not be a priority at the moment as the chat itself is a bit broken after we moved to Remix. It should only be visible on the /contact page, but I'm not sure if that's the case at the moment.
Feel free to work on that, but if you'd like to contribute in some other way, I'd suggest the following tasks (they're not too difficult and perfect for people who are just getting to know our codebase):
- https://github.com/Swetrix/roadmap/issues/161 - add a textarea element to the account deletion confirmation modal to collect feedback (and create a `deletion_feedback` table in our database to store it (we can help you with this)).
- https://github.com/Swetrix/roadmap/issues/165

**Comment by Pranavvks** [comment]
Hi @Blaumaus. 

Thank you for the detailed response. Finally after making changes to the swetrix-fe env config , I have got the project working 🥳. The API_URL parameter that I had intially set was pointing to the backend service running in port 8080.  
> Also @Pranavvks, this may not be a priority at the moment as the chat itself is a bit broken after we moved to Remix. It should only be visible on the /contact page, but I'm not sure if that's the case at the moment. Feel free to work on that, but if you'd like to contribute in some other way, I'd suggest the following tasks (they're not too difficult and perfect for people who are just getting to know our codebase):
> 
> * [Improve account deletion process #161](https://github.com/Swetrix/roadmap/issues/161) - add a textarea element to the account deletion confirmation modal to collect feedback (and create a `deletion_feedback` table in our database to store it (we can help you with this)).
> * [If for the last 2-3 month there has been 0 pageviews on users project - the email reports frequency should be set to none #165](https://github.com/Swetrix/roadmap/issues/165)

If that's the case, then I am willing to take up issue : #161. Please do assign it to me.

**Comment by Blaumaus** [comment]
@Pranavvks I can't assign that task to you unless you leave a comment there (some sort of Github restrictions). Please do that and I'll assign it to you afterwards
